# Generated by Django 5.1.2 on 2025-01-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.IntegerField(),
        ),
    ]
